-- ============================================================================
-- PASO 6: FORCE ROW LEVEL SECURITY en TODAS las tablas con institutionId
-- FORCE hace que RLS aplique incluso al table owner (postgres/prisma).
-- Esto es el máximo nivel de aislamiento multi-tenant.
-- ============================================================================
-- IMPORTANTE: El backend DEBE setear app.current_institution ANTES de cada query.
-- Sin esto, todas las queries fallarán (retornarán 0 filas).
-- ============================================================================

-- Tablas que ya tenían institutionId desde antes (del enable_rls.sql original)
ALTER TABLE "InstitutionModule" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InstitutionUser" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Campus" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Area" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AcademicTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AcademicYear" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PerformanceScale" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EvaluationComponent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Student" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Guardian" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinalComponent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Message" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Announcement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GalleryImage" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Event" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RecoveryConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AcademicAct" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PerformanceLevelComplement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PerformanceConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AchievementConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AchievementBank" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PermissionAuditLog" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ElectionProcess" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PaymentConcept" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PaymentEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InstitutionalDocument" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ManagementLeader" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ManagementTask" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InstitutionStorageUsage" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialThirdParty" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialCategory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ChargeConcept" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialObligation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialPayment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialExpense" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialInvoice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialSettings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CashRegisterClose" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TimeBlock" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Room" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ScheduleGradeConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TeacherAvailability" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ScheduleEntry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ReportCardConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InstitutionRoleCapability" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Institution" FORCE ROW LEVEL SECURITY;

-- Nuevas 26 tablas (Paso 5 habilitó RLS, ahora FORCE)
ALTER TABLE "StudentEnrollment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TeacherAssignment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EnrollmentArea" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EnrollmentSubject" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EnrollmentDimension" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EnrollmentEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "StudentGrade" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PeriodFinalGrade" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PartialGrade" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinalComponentGrade" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PreventiveAlert" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AttendanceRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "StudentObservation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ObserverCommitment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GuardianCitation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ObserverReferral" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PedagogicalMeasure" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EvaluativeActivity" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SubjectPerformance" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PerformanceManualEdit" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Achievement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AttitudinalAchievement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "StudentAchievement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PeriodRecovery" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinalRecoveryPlan" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RoomRestriction" FORCE ROW LEVEL SECURITY;
